[package]
name = "hacker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
itertools = "0.10.5"
pest = "2.5.3"
pest_derive = "2.5.3"
